version: '3'
volumes:
  postgres_volume:

services:
  postgres:
      container_name: postgres
      image: postgres:11
      volumes:
        - postgres_volume:/var/lib/postgresql/data/
      env_file:
        - .env
      ports:
        - "5432:5432"
  web:
    container_name: web
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres