# Generated by Django 3.1.2 on 2020-10-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('published_date', models.DateField(null=True)),
                ('isbn_number', models.IntegerField(null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('thumbnail', models.URLField(max_length=255, null=True)),
                ('language', models.CharField(max_length=10, null=True)),
                ('authors', models.ManyToManyField(related_name='authors', to='book_list.Author')),
            ],
        ),
    ]
