# Generated by Django 3.1.2 on 2020-10-21 19:18

import django.core.validators
from django.db import migrations, models

import book_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("authors", models.CharField(max_length=150, null=True)),
                (
                    "published_date",
                    models.IntegerField(
                        null=True, validators=[book_list.models.validate_year]
                    ),
                ),
                ("isbn_number", models.CharField(max_length=13, null=True)),
                ("page_count", models.IntegerField(null=True)),
                (
                    "thumbnail",
                    models.URLField(
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.URLValidator],
                    ),
                ),
                ("language", models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
