# Generated by Django 3.1.2 on 2020-10-21 18:02

import book_list.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(max_length=13, null=True, validators=[book_list.models.validate_isbn]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.IntegerField(null=True, validators=[book_list.models.validate_year]),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(max_length=255, null=True, validators=[django.core.validators.URLValidator]),
        ),
    ]
