# Generated by Django 3.1.2 on 2020-10-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0003_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
