# Generated by Django 3.1.2 on 2020-10-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0004_auto_20201020_1413'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
